apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-ml
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: EFS_ID_PLACEHOLDER   # replaced by sed in Step 1
  directoryPerms: "700"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"
  basePath: "/ml-workloads"
reclaimPolicy: Retain
volumeBindingMode: Immediate
